### ISSUE TITLE
Adding LST selection in aartfaac2ms

### ISSUE THREAD

**Issue by kbharatgehlot** [aroffringa/aartfaac2ms#1]
Hi Andre,

An LST selection parameter in aartfaac2ms would be a great way to perform LST binning which we require for all future analyses of the ACE data. I require something like this:

1. A small function (or an inbuilt tool) which returns LST range of the input raw data. This is useful to keep track of the LST range of each observation.

2. Two input parameters to select the LST range for conversion e.g. 
(a) --start-lst and --duration 
or (b) --start-lst and --end-lst

**Comment by aroffringa** [comment]
Thanks Bharat, I'll implement this. It will take a couple of weeks though.
