### ISSUE TITLE
Data seems malformed after UTC cut 

### ISSUE THREAD

**Issue by mkuiack** [aroffringa/aartfaac2ms#11]
I've tested PR/10 by selecting a slice of data using the -utc-start/-utc-end. I processed the data with the same method I was previously using, same parsets etc. 
The resulting images possibly show some mixed up phase centre in the data. The image attached is a single timestep, with three frequency channels calibrated independently in DPPP integrated with WSClean 

In the meantime I will test whether using  -trim-start/-trim-end on the same data produce the same results. 

<img width="453" alt="Screen Shot 2020-08-21 at 11 00 20" src="https://user-images.githubusercontent.com/14295490/90873463-7f66c180-e39e-11ea-9220-555a32b68fb3.png">

**Comment by aroffringa** [comment]
@mkuiack it also happens when you use the old aartfaac2ms en afedit? (before the recent changes)

**Comment by mkuiack** [comment]
No I've rolled back to the previous version, prior to PR/10, and verified that I don't see this issue when slicing the same interval of data.  
@tammojan have you been able to reproduce this with the chunk of data I sent you?

**Comment by tammojan** [comment]
No, I have not been able to reproduce this...

I checked that the following commands produce the same output:
```
afedit -utc-start 2020-08-12T21:25:00 -utc-end 2020-08-12T21:25:30 SB256-20200812T212413-212713.vis SB256-utc_select_212500-212530.vis

aartfaac2ms -mode 1 -interval 23 38 SB256-20200812T212413-212713.vis SB256-aartfaac2ms_select_212500-212530.MS A12-AntennaField.conf

taql 'select gmean(abs(a.TIME - b.TIME)), gmean(abs(a.DATA[FLAG] - b.DATA[FLAG])), gmean(abs(a.UVW - b.UVW)), gntrue(a.FLAG), gntrue(b.FLAG) from SB256-utc_select_212500-212530.MS a, SB256-aartfaac2ms_select_212500-212530.MS b'
0	0	0	0     0
```

I have tried imaging the uncalibrated data, but probably made a bug somewhere because all images look the same. I don't see any aliases though (only one clear copy of CasA and CygA).

**Comment by mkuiack** [comment]
That is strange, the visibility I sent you was already clipped, and should have shown the issue if you directly converted it to ms and made the uncalibrated images. I am setting the -flag and -use-dysco parameters in aartfaac2ms. I will do some more experiments with the PR/10 version and see if I can figure anything out. Also I'm using the LOFAR cookbook singularity image for all my dependencies, which might be out of date compared to what you're using. 

WSClean version 2.7.0 (2019-04-19)
AOFlagger 2.14.0 (2019-02-14)

**Comment by mkuiack** [comment]
I've resolved my issue. After all it wasn't a problem with PR/10. 
I was cmaking with `-DBoost_NO_BOOST_CMAKE=ON` because my horribly outdated version of cmake wasn't finding the boost components. 
I sorted it out by making appropriately named links to the boost_python libraries and directing cmake there.  
Using the lofar cookbook singularity image: 

> cmake .. -DPYTHON_INCLUDE_DIR=/opt/lofarsoft/include/ 
-DBoost_PYTHON36_LIBRARY=/home/mkuiack1/soft/src/boostlibdir/libboost_python36.so 
-DCASACORE_ROOT_DIR=/opt/lofarsoft 
-DAOFLAGGER_INCLUDE_DIR=/opt/lofarsoft/include 
-DAOFLAGGER_LIB=/opt/lofarsoft/lib/libaoflagger.so

**Comment by aroffringa** [comment]
Great that it is solved, although I highly suspect it's not due to Boost. It's more or less impossible that it could cause something like this... rather it was probably something in your linked, e.g. with casacore, which got solved in your recompile. But anyway, good that it is solved :).
