### ISSUE TITLE
Cannot install with LOFAR cookbook singularity image 

### ISSUE THREAD

**Issue by mkuiack** [aroffringa/aartfaac2ms#12]
AOflagger dependence is causing a lot of headaches, The LOFAR cookbook container only has AOflagger 2, 
I manually changed the required version in the CMakeList, but get these errors. 
```
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindAOFlagger.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "AOFlagger", but CMake did not find one.

  Could not find a package configuration file provided by "AOFlagger"
  (requested version 2) with any of the following names:

    AOFlaggerConfig.cmake
    aoflagger-config.cmake

  Add the installation prefix of "AOFlagger" to CMAKE_PREFIX_PATH or set
  "AOFlagger_DIR" to a directory containing one of the above files.  If
  "AOFlagger" provides a separate development package or SDK, be sure it has
  been installed.
```

I'm defining the aoflagger library and include dir in the cmake commands:
```
cmake .. -DPYTHON_INCLUDE_DIR=/opt/lofarsoft/include/    \
-DBoost_PYTHON36_LIBRARY=$HOME/libboost_python.so \
-DCASACORE_ROOT_DIR=/opt/lofarsoft \
-DAOFLAGGER_INCLUDE_DIR=/opt/lofarsoft/include \
-DAOFLAGGER_LIB=/opt/lofarsoft/lib/libaoflagger.so
```

**Comment by mkuiack** [comment]
Need to rollback to a previous commit to use with AOflagger 2, and have the UTC functionality:
```
git reset --hard 682bbb77b98480888964841253dff4498876c835 
```

Maybe this one could be tagged?

**Comment by aroffringa** [comment]
This sounds more like a 'lofar cookbook singularity image' then an issue of aartfaac2ms ;). It sounds like that image is out of date.

I've tagged a 'before-aoflagger3' version with the hash you provided. There are however newer commits that don't require the aoflagger 3 dependency, wouldn't have 682bbb77b98480888964841253dff4498876c835 be a better version?

**Comment by mkuiack** [comment]
Thanks, yes this is only an issue because the LOFAR containers we're using aren't up to date. 
Thanks also for adding the tag. That version might have been better but the difference doesn't seem critical.
