### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by gijzelaerr** [aroffringa/aartfaac2ms#3]
I can add aartfaac2ms to KERN, but packages work better with software with versions. Is it possible someone just presses the release button on github? That would simplify my life.

thanks!

**Comment by aroffringa** [comment]
Sure. Happy to press release once #5 is confirmed to be fixed for you (I don't get that the same error somehow).

**Comment by gijzelaerr** [comment]
#5 is solved, I can successfully build a package now, thanks!

**Comment by aroffringa** [comment]
Done: https://github.com/aroffringa/aartfaac2ms/releases/tag/v1.0
