### ISSUE TITLE
Using aartfaac2ms  -interval <start> <end> deletes OBS-DATE

### ISSUE THREAD

**Issue by mkuiack** [aroffringa/aartfaac2ms#8]
Currently using version 0.4 (2020-07-11). 
After calibration with DPPP and imaging with WSClean  DATE-OBS= ‘1858-11-17T00:00:00.0’ in all of the images. 

When first trimming the .vis with afedit, then converting the trimmed .vis to and ms results in images with the correct datetime. 

Also, for the transient follow-up case, it would be nice if slices could be selected with start and end time in UTC. 
and if the UTC range of the .vis could be read before conversion.

**Comment by tammojan** [comment]
I cannot reproduce the erroneous `DATE-OBS`, when I run
```
aartfaac2ms -interval 1 4 -mode 1 SB167-202008122000-lba_inner-trim10.vis test.MS A12-AntennaField.conf
DPPP msin=test.MS msout=out.MS steps=[]
wsclean -size 1200 1200 -scale 1deg -name quick out.MS
python3 -c 'from astropy.io import fits; print(fits.open("quick-image.fits")[0].header["DATE-OBS"])'
```
I get a correct result
```
2020-08-13T00:10:01.0
```

Pull request #10 adds some functionality to `afedit` to show UTC times and select based on UTC times.

**Comment by mkuiack** [comment]
I am using the LOFAR cookbook singularity image 
https://support.astron.nl/LOFARImagingCookbook/buildlofar.html#how-to-import-the-docker-image-inside-singularity
for all dependencies, casa and aoflagger as well as DPPP and WSCLean. It's a bit out of date I think, maybe that is causing the issue for me. 

Thank you, I will test the PR.

**Comment by mkuiack** [comment]
After more experimenting, I find this isn't an AFedit or aartfaac2ms issue.
